#ifndef grad_argmax_14_SCHEDULE_H
#define grad_argmax_14_SCHEDULE_H

// MACHINE GENERATED -- DO NOT EDIT
// This schedule was automatically generated by Adams2019
// for target=arm-64-linux-enable_llvm_loop_opt  // NOLINT
// with autoscheduler_params=autoscheduler=Adams2019

#include "Halide.h"


inline void apply_schedule_grad_argmax_14(
    ::Halide::Pipeline pipeline,
    ::Halide::Target target
) {
    using ::Halide::Func;
    using ::Halide::MemoryType;
    using ::Halide::RVar;
    using ::Halide::TailStrategy;
    using ::Halide::Var;
    Func local_max_y = pipeline.get_func(5);
    Func argmax_1 = pipeline.get_func(4);
    Func local_max_x = pipeline.get_func(2);
    Func argmax = pipeline.get_func(1);
    Var v0(local_max_y.get_schedule().dims()[0].var);
    Var v0i("v0i");
    Var v0ii("v0ii");
    Var v1(local_max_y.get_schedule().dims()[1].var);
    Var v2(local_max_y.get_schedule().dims()[2].var);
    RVar r_tile_x(argmax_1.update(0).get_schedule().dims()[0].var);
    RVar r_tile_y(argmax_1.update(0).get_schedule().dims()[1].var);
    local_max_y
        .split(v0, v0, v0i, 16, TailStrategy::ShiftInwards)
        .split(v0i, v0i, v0ii, 8, TailStrategy::ShiftInwards)
        .vectorize(v0ii)
        .compute_root()
        .reorder({v0ii, v0i, v2, v0, v1})
        .fuse(v0, v1, v0)
        .parallel(v0);
    argmax_1
        .split(v0, v0, v0i, 4, TailStrategy::RoundUp)
        .unroll(v0)
        .vectorize(v0i)
        .compute_at(local_max_y, v0)
        .reorder({v0i, v0, v1});
    argmax_1.update(0)
        .split(v0, v0, v0i, 4, TailStrategy::GuardWithIf)
        .unroll(v0)
        .vectorize(v0i)
        .reorder({v0i, v0, v1, r_tile_x, r_tile_y});
    local_max_x
        .split(v0, v0, v0i, 16, TailStrategy::ShiftInwards)
        .split(v0i, v0i, v0ii, 8, TailStrategy::ShiftInwards)
        .vectorize(v0ii)
        .compute_root()
        .reorder({v0ii, v0i, v2, v0, v1})
        .fuse(v0, v1, v0)
        .parallel(v0);
    argmax
        .split(v0, v0, v0i, 4, TailStrategy::RoundUp)
        .unroll(v0)
        .vectorize(v0i)
        .compute_at(local_max_x, v0)
        .reorder({v0i, v0, v1});
    argmax.update(0)
        .split(v0, v0, v0i, 4, TailStrategy::GuardWithIf)
        .unroll(v0)
        .vectorize(v0i)
        .reorder({v0i, v0, v1, r_tile_x, r_tile_y});

}

#endif  // grad_argmax_14_SCHEDULE_H
