#ifndef grad_xy_SCHEDULE_H
#define grad_xy_SCHEDULE_H

// MACHINE GENERATED -- DO NOT EDIT
// This schedule was automatically generated by Adams2019
// for target=x86-64-linux-avx-avx2-enable_llvm_loop_opt-f16c-fma-sse41  // NOLINT
// with autoscheduler_params=autoscheduler=Adams2019

#include "Halide.h"


inline void apply_schedule_grad_xy(
    ::Halide::Pipeline pipeline,
    ::Halide::Target target
) {
    using ::Halide::Func;
    using ::Halide::MemoryType;
    using ::Halide::RVar;
    using ::Halide::TailStrategy;
    using ::Halide::Var;
    Func grad_y = pipeline.get_func(4);
    Func grad_x = pipeline.get_func(3);
    Func repeat_edge = pipeline.get_func(2);
    Func lambda_0 = pipeline.get_func(1);
    Var _0(repeat_edge.get_schedule().dims()[0].var);
    Var _0i("_0i");
    Var _1(repeat_edge.get_schedule().dims()[1].var);
    Var _1i("_1i");
    Var v0(grad_y.get_schedule().dims()[0].var);
    Var v0i("v0i");
    Var v1(grad_y.get_schedule().dims()[1].var);
    Var v1i("v1i");
    grad_y
        .split(v1, v1, v1i, 45, TailStrategy::GuardWithIf)
        .split(v0, v0, v0i, 32, TailStrategy::ShiftInwards)
        .vectorize(v0i)
        .compute_root()
        .reorder({v0i, v0, v1i, v1})
        .parallel(v1);
    grad_x
        .split(v1, v1, v1i, 45, TailStrategy::GuardWithIf)
        .split(v0, v0, v0i, 32, TailStrategy::ShiftInwards)
        .vectorize(v0i)
        .compute_root()
        .reorder({v0i, v0, v1i, v1})
        .parallel(v1);
    repeat_edge
        .split(_1, _1, _1i, 46, TailStrategy::ShiftInwards)
        .split(_0, _0, _0i, 32, TailStrategy::ShiftInwards)
        .vectorize(_0i)
        .compute_root()
        .reorder({_0i, _0, _1i, _1})
        .parallel(_1);

}

#endif  // grad_xy_SCHEDULE_H
