#ifndef image_warp_SCHEDULE_H
#define image_warp_SCHEDULE_H

// MACHINE GENERATED -- DO NOT EDIT
// This schedule was automatically generated by Adams2019
// for target=x86-64-linux-avx-avx2-enable_llvm_loop_opt-f16c-fma-sse41  // NOLINT
// with autoscheduler_params=autoscheduler=Adams2019

#include "Halide.h"


inline void apply_schedule_image_warp(
    ::Halide::Pipeline pipeline,
    ::Halide::Target target
) {
    using ::Halide::Func;
    using ::Halide::MemoryType;
    using ::Halide::RVar;
    using ::Halide::TailStrategy;
    using ::Halide::Var;
    Func output = pipeline.get_func(4);
    Func clamped = pipeline.get_func(3);
    Func repeat_edge = pipeline.get_func(2);
    Func lambda_0 = pipeline.get_func(1);
    Var _0(repeat_edge.get_schedule().dims()[0].var);
    Var _0i("_0i");
    Var _1(repeat_edge.get_schedule().dims()[1].var);
    Var v0(output.get_schedule().dims()[0].var);
    Var v0i("v0i");
    Var v0ii("v0ii");
    Var v1(output.get_schedule().dims()[1].var);
    Var v1i("v1i");
    output
        .split(v1, v1, v1i, 23, TailStrategy::GuardWithIf)
        .split(v0, v0, v0i, 96, TailStrategy::GuardWithIf)
        .split(v0i, v0i, v0ii, 32, TailStrategy::ShiftInwards)
        .vectorize(v0ii)
        .compute_root()
        .reorder({v0ii, v0i, v1i, v0, v1})
        .parallel(v1);
    clamped
        .store_in(MemoryType::Stack)
        .split(v0, v0, v0i, 32, TailStrategy::RoundUp)
        .vectorize(v0i)
        .compute_at(output, v0i)
        .reorder({v0i, v0, v1});
    repeat_edge
        .store_in(MemoryType::Stack)
        .split(_0, _0, _0i, 32, TailStrategy::ShiftInwards)
        .vectorize(_0i)
        .compute_at(output, v0)
        .reorder({_0i, _0, _1});

}

#endif  // image_warp_SCHEDULE_H
