#ifndef pyr_down_SCHEDULE_H
#define pyr_down_SCHEDULE_H

// MACHINE GENERATED -- DO NOT EDIT
// This schedule was automatically generated by Adams2019
// for target=x86-64-linux-avx-avx2-enable_llvm_loop_opt-f16c-fma-sse41  // NOLINT
// with autoscheduler_params=autoscheduler=Adams2019

#include "Halide.h"


inline void apply_schedule_pyr_down(
    ::Halide::Pipeline pipeline,
    ::Halide::Target target
) {
    using ::Halide::Func;
    using ::Halide::MemoryType;
    using ::Halide::RVar;
    using ::Halide::TailStrategy;
    using ::Halide::Var;
    Func output = pipeline.get_func(5);
    Func blur_xy = pipeline.get_func(4);
    Func blur_y = pipeline.get_func(3);
    Func repeat_edge = pipeline.get_func(2);
    Func lambda_0 = pipeline.get_func(1);
    Var _0(repeat_edge.get_schedule().dims()[0].var);
    Var _0i("_0i");
    Var _1(repeat_edge.get_schedule().dims()[1].var);
    Var x(output.get_schedule().dims()[0].var);
    Var xi("xi");
    Var xii("xii");
    Var xiii("xiii");
    Var y(output.get_schedule().dims()[1].var);
    Var yi("yi");
    output
        .split(x, x, xi, 320, TailStrategy::GuardWithIf)
        .split(y, y, yi, 12, TailStrategy::ShiftInwards)
        .split(xi, xi, xii, 64, TailStrategy::ShiftInwards)
        .split(xii, xii, xiii, 32, TailStrategy::ShiftInwards)
        .unroll(xii)
        .vectorize(xiii)
        .compute_root()
        .reorder({xiii, xii, yi, xi, x, y})
        .fuse(x, y, x)
        .parallel(x);
    blur_xy
        .store_in(MemoryType::Stack)
        .split(x, x, xi, 8, TailStrategy::RoundUp)
        .unroll(x)
        .vectorize(xi)
        .compute_at(output, xii)
        .reorder({xi, x, y});
    blur_y
        .store_in(MemoryType::Stack)
        .split(x, x, xi, 32, TailStrategy::RoundUp)
        .unroll(x)
        .vectorize(xi)
        .compute_at(output, yi)
        .reorder({xi, x, y});
    repeat_edge
        .store_in(MemoryType::Stack)
        .split(_0, _0, _0i, 32, TailStrategy::ShiftInwards)
        .vectorize(_0i)
        .compute_at(output, yi)
        .store_at(output, xi)
        .reorder({_0i, _0, _1});

}

#endif  // pyr_down_SCHEDULE_H
