#ifndef sparse_warpdiff_SCHEDULE_H
#define sparse_warpdiff_SCHEDULE_H

// MACHINE GENERATED -- DO NOT EDIT
// This schedule was automatically generated by Adams2019
// for target=x86-64-linux-avx-avx2-enable_llvm_loop_opt-f16c-fma-sse41  // NOLINT
// with autoscheduler_params=autoscheduler=Adams2019

#include "Halide.h"


inline void apply_schedule_sparse_warpdiff(
    ::Halide::Pipeline pipeline,
    ::Halide::Target target
) {
    using ::Halide::Func;
    using ::Halide::MemoryType;
    using ::Halide::RVar;
    using ::Halide::TailStrategy;
    using ::Halide::Var;
    Func output = pipeline.get_func(5);
    Func repeat_edge = pipeline.get_func(4);
    Func lambda_0 = pipeline.get_func(3);
    Var v0(output.get_schedule().dims()[0].var);
    Var v0i("v0i");
    Var v1(output.get_schedule().dims()[1].var);
    Var v1i("v1i");
    output
        .split(v0, v0, v0i, 32, TailStrategy::GuardWithIf)
        .split(v1, v1, v1i, 2, TailStrategy::GuardWithIf)
        .unroll(v1i)
        .vectorize(v0i)
        .compute_root()
        .reorder({v0i, v1i, v0, v1})
        .fuse(v0, v1, v0)
        .parallel(v0);

}

#endif  // sparse_warpdiff_SCHEDULE_H
