#ifndef sparse_jac_SCHEDULE_H
#define sparse_jac_SCHEDULE_H

// MACHINE GENERATED -- DO NOT EDIT
// This schedule was automatically generated by Adams2019
// for target=arm-64-linux-enable_llvm_loop_opt  // NOLINT
// with autoscheduler_params=autoscheduler=Adams2019

#include "Halide.h"


inline void apply_schedule_sparse_jac(
    ::Halide::Pipeline pipeline,
    ::Halide::Target target
) {
    using ::Halide::Func;
    using ::Halide::MemoryType;
    using ::Halide::RVar;
    using ::Halide::TailStrategy;
    using ::Halide::Var;
    Func output_y = pipeline.get_func(5);
    Func output_x = pipeline.get_func(2);
    Var v0(output_y.get_schedule().dims()[0].var);
    Var v0i("v0i");
    Var v1(output_y.get_schedule().dims()[1].var);
    Var v1i("v1i");
    Var v2(output_y.get_schedule().dims()[2].var);
    Var v2i("v2i");
    output_y
        .split(v1, v1, v1i, 7, TailStrategy::ShiftInwards)
        .split(v2, v2, v2i, 2, TailStrategy::ShiftInwards)
        .split(v0, v0, v0i, 8, TailStrategy::ShiftInwards)
        .vectorize(v0i)
        .compute_root()
        .reorder({v0i, v0, v1i, v2i, v1, v2})
        .fuse(v1, v2, v1)
        .parallel(v1);
    output_x
        .split(v1, v1, v1i, 7, TailStrategy::ShiftInwards)
        .split(v2, v2, v2i, 2, TailStrategy::ShiftInwards)
        .split(v0, v0, v0i, 8, TailStrategy::ShiftInwards)
        .vectorize(v0i)
        .compute_root()
        .reorder({v0i, v0, v1i, v2i, v1, v2})
        .fuse(v1, v2, v1)
        .parallel(v1);

}

#endif  // sparse_jac_SCHEDULE_H
